name: publish-site

on:
  workflow_run:
    workflows:
      - verify
    types:
      - completed
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'

env:
  TZ: America/Indianapolis

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'

      - run: mvn --batch-mode package -DskipTests

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: target/iu-site.tar
          retention-days: 1

  publish-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: github_pages

      - uses: actions/download-artifact@v3
        with:
          name: site

      - run: |
          echo $GITHUB_REF_NAME
          ls -l $(find -type f)
          git status

