name: publish

on:
  workflow_run:
    workflows:
      - verify
    types:
      - completed
    branches:
      - 'main'
      - 'develop'

env:
  TZ: America/Indianapolis

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'
          server-id: IUMaven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - run: mvn --batch-mode deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.IUMAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.IUMAVEN_TOKEN }}

